prometheus
MrCroxx/RunKV pull request #122
Opened 2022-04-28 11:07 UTC by ytaoeer

2022-04-28 11:08 UTC, ytaoeer commented
prometheus

2022-04-29 02:18 UTC, MrCroxx commented
Thank you for your contribution. Please refine the PR title and message. Describe the motivation of this pull request, what changed in this PR and list references of related issues and PRs.

2022-04-29 02:33 UTC, MrCroxx requested changes

2022-04-29 02:33 UTC, MrCroxx commented on common/src/config.rs
> +// prometheus config
Remove the comment.

2022-04-29 02:33 UTC, MrCroxx commented on make/grafana.toml
> +#condition = { env_set = [ "ENABLE_PROMETHEUS_GRAFANA" ] }
Remove the comment.

2022-04-29 02:33 UTC, MrCroxx commented on Makefile.toml
> +extend = [{ path = "make/common.toml" }, { path = "make/minio.toml" }, { path = "make/jaeger.toml" },{ path = "make/prometheus.toml"}]
Add `grafana.toml` here.

2022-04-29 02:33 UTC, MrCroxx commented on Makefile.toml
> +dependencies = ["download-minio", "download-mcli","download-prometheus", "clean-data"]
Ditto.

2022-04-29 02:33 UTC, MrCroxx commented on make/grafana.toml
> +#rm "${GRAFANA_DOWNLOAD_PATH}"
Why comment this line? If you don't need it please just remove it.

2022-04-29 02:33 UTC, MrCroxx commented on make/prometheus.toml
> +#rm ${PROMETHEUS_DOWNLOAD_PATH}
Ditto.

2022-04-29 02:33 UTC, MrCroxx commented on make/prometheus.yml
> +# my global config
Configuration files should not be kept in `make` directory. `make` directory is used to keep make scripts. Please move this file to `etc`.

Besides, remove the comment.

2022-04-29 02:33 UTC, MrCroxx commented on make/prometheus.yml
> +# my global config
Besides, remove all **unused** comments and fields in this file.

2022-04-29 02:33 UTC, MrCroxx commented on make/prometheus.yml
> +# my global config
BTW, `tests/etc` also need one copy of this file.

2022-04-29 02:33 UTC, MrCroxx commented on make/prometheus.yml
> +      - targets: ["192.168.105.132:9898"]
Please don't include ip address of your development environment. If this file is a configuration template, use localhost or "127.0.0.1" instead.

2022-04-29 02:33 UTC, MrCroxx commented on tests/etc/wheel.toml
> +host = "192.168.105.132"
Ditto.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/Cargo.toml
> +log = "0.4.16"
We don't need `log` crate. In RunKV we use `tracing` to record event and span logs. Please remove the dependency.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/config.rs
> +use runkv_common::config::{CacheConfig, LsmTreeConfig, MinioConfig, Node, S3Config,PrometheusConfig};
Please make sure you've lint the code.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +// prometheus
Remove the comment.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +}
Please refactor the field names with meaningful description.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +    let listen_addr: String = format!("{}:{}", config.prometheus.host, config.prometheus.port);
```suggestion
    let listen_addr = format!("{}:{}", config.prometheus.host, config.prometheus.port);
```

Please remove unnecessary type identifier.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +        log::info!("every second update example_num and exampe_time");
Use tracing instead.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +}
Why we need test here?

1. Tests should not be placed in `lib.rs`, it's only used for building and bootstrapping nodes.
2. I think we don't need to unit test to test if prometheus works. Besides, this test cannot give you any useful feedbacks.
3. If you want to add a unit test, Please use `#[cfg(test)]` `#[test]` and wrap them in `tests` module to make it only available when testing. Please refer to the Rust book.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +        log::info!(
Ditto.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/lib.rs
> +            eprintln!("server error: {}", err);
Ditto.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/service.rs
> +use log::info;
Ditto.

2022-04-29 02:33 UTC, MrCroxx commented on wheel/src/service.rs
> +// prometheus
Remove the comment.

2022-04-29 12:10 UTC, MrCroxx commented on wheel/Cargo.toml
> +
Remove the empty line. BTW, have you run `make fmt` first?

2022-04-29 12:11 UTC, MrCroxx commented on wheel/src/lib.rs
> +        let listen_prometheus_addr: SocketAddr = listen_addr.parse().unwrap();
Not sure if this type identifier can be removed.

2022-04-29 12:54 UTC, MrCroxx approved these changes
LGTM!

2022-04-29 12:54 UTC, MrCroxx commented on Makefile.toml
> +tmux new -d -s runkv-prometheus "${PREFIX_BIN}/prometheus/prometheus" --config.file="${PWD}/tests/etc/prometheus.yml" --web.listen-address=:9091 --storage.tsdb.path="${PREFIX_DATA}/prometheus_data"
`$PWD` should be removed. Or if we run `run` from other directory, it will refer to wrong directory. 🤔

2022-04-30 02:09 UTC, merged